config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/top'
  get 'home/about'
  root to: 'home#top'
    resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # 追加ここから
  belongs_to :user # 追加
  validates :title, presence: true # タイトルの入力は必須
  validates :body, presence: true, length: { maximum: 200 } # 感想の入力は必須で200文字以下
  ## 追加ここまで
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  # 追加ここから 
  has_many :books, dependent: :destroy # 追加
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true # 名前の入力は2文字以上20文字以下で、unique
  validates :introduction, presence: false, length: { maximum: 50 } # 自己紹介の入力は必須で、50文字以下
  # 追加ここまで
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  # 追加ここから
  def after_sign_in_path_for(resource)
    user_path(current_user) # ログインしたユーザーの詳細へ遷移
  end
  # 追加ここまで

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @user = current_user
    @new_book = Book.new
    @errors = flash[:errors] || []
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    
    if @book.save
      redirect_to @book, notice: 'You have created book successfully.'
    else
      redirect_to books_path, flash: { errors: @book.errors.full_messages }
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end  
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end 
    if @book.update(book_params)
      redirect_to @book, notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end  
  
    
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
 
  private 
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @new_book = Book.new
  end

  def show
    # ここから追記 
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
    # ここまで追記
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to current_user
    end  
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to @user
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class='container'>
    <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>  
      </ul>
    </div>
    <% end %>
    <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <%= form_with model: @book, local:true do |f| %>
          <div class="form-group">
            <%= f.label :title, 'Title' %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :body, 'Opinion' %>   
            <%= f.text_area :body, class: "form-control" %>
          </div>
          <div class="form-group">
             <%= f.submit 'Update Book', class: "btn btn-success" %>
          </div>
         <% end %>
        
        <%= link_to 'Show', @book %> | 
        <%= link_to 'Back', books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>
  <div class='container px-5 px-sm-0'>
    <div class='container px-5 px-sm-0'>
      <% if @errors.any? %>
      <div id="error_explanation">
        <h3><%= @errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @errors.each do |message| %>
            <li><%= message %></li>
          <% end %>  
        </ul>
      </div>
    <% end %>
    <div class='row'>
      <%= render 'layouts/left', user: @user, book: @new_book %>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to book.user do %>
                  <%= attachment_image_tag book.user, :profile_image, size: "80x80", format: 'jpeg', fallback:"default-image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <%= render 'layouts/left', user: @book.user, book: @new_book %>
      <div class='col-md-8 offset-md-1'>
        <h2>Book detail</h2>
        <table class='table'>
          <tr>
            <td>
              <%= link_to @book.user do %>
                <%= attachment_image_tag @book.user, :profile_image, size: "100x100", format: 'jpeg', fallback:"default-image.jpg" %>
                <br><%= @book.user.name %> 
              <% end %>
            </td>
            <td>
              <%= link_to @book.title, @book %>
            </td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td>
              <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-sm btn-success' %>
            </td>
            <td>
              <%= link_to "Destroy", book_path(@book), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: "本当に消しますか？" } %>
            </td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/home/about.html.erb
<main>
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to 
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/home/top.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to 
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>!!
        </h1>
        <p>In 
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
             <a class="nav-link text-light" href="/users/<%= current_user.id %>">
              <i class="fas fa-home"></i>Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users">
              <i class="fas fa-users"></i>Users
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/books">
              <i class="fas fa-book-open"></i>Books
            </a>
          </li>
          <li>
            <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fas fa-sign-out-alt"></i>Log out
            </a>
          </li>
          <% else %>
          <li>
            <a class="nav-link text-light" href="/">
              <i class="fas fa-home"></i>Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/home/about">
              <i class="fas fa-link"></i>About
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus"></i>Sign up
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>Log in
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_left.html.erb
<div class='col-md-3'>
  <h2>User info</h2>
  <table class='table'>
    <tr>
      <%= attachment_image_tag user, :profile_image, size: "100x100", format: 'jpeg', fallback:"default-image.jpg" %>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </table>　 
  <div class='row'>
    <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  
  <%= form_with model: book, url:'/books', local:true do |f| %>
    <div class="form-group">
      <%= f.label :title, 'Title' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :body, 'Opinion' %>   
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group">
       <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
   <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/edit.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>  
      </ul>
    </div>
    <% end %>
    <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :profile_image, 'Image' %>
          <%= f.attachment_field :profile_image, class: "form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, 'Introduction' %>   
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
           <%= f.submit 'Update User', class: "btn btn-secondary" %>
        </div>
       <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
     <%= render 'layouts/left', user: @user, book: @new_book %>
      <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <table class='table'>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, size: "80x80", format: 'jpeg', fallback:"default-image.jpg" %>
              </td>
              <td><%= user.name %></td>
              <td>
                <%= link_to 'Show', user %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <%= render 'layouts/left', user: @user, book: @new_book %>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to @user do %>
                  <%= attachment_image_tag book.user, :profile_image, size: "80x80", format: 'jpeg', fallback:"default-image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>